[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "EncryptedERC/=lib/EncryptedERC/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"
mainnet = "https://api.avax.network/ext/bc/C/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
